# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - ChattingApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-dev default-libmysqlclient-dev build-essential

      - name: Create and start virtual environment
        run: |
          pip3 install virtualenv
          virtualenv -p /usr/bin/python3 venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade setuptools
          pip install mysqlclient
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Run database migrations
        run: |
          source venv/bin/activate
          python3 fundoo/manage.py makemigrations
          python3 fundoo/manage.py migrate

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "*.git/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'ChattingApp'
          slot-name: 'Production'

      - name: Run application
        run: |
          source venv/bin/activate
          cd fundoo
          gunicorn --bind 0.0.0.0:8000 fundoo.wsgi:application
